-- AlterEnum DocumentType
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'GST_CERT';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'CREATIVE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'WALKTHROUGH';

-- AlterTable Lead
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "siteVisitDate" TIMESTAMP(3);
